prompt user before allowing location access
MetaMask/react-native-webview-mm pull request #9
Opened 2024-02-27 13:09 UTC by jpcloureiro

2024-03-06 15:29 UTC, jpcloureiro commented
depends on #8.

ready to review after rebase

2024-03-07 16:54 UTC, tommasini requested changes

2024-03-07 16:54 UTC, tommasini commented on android/src/main/java/com/reactnativecommunity/webview/RNCWebChromeClient.java
> +            alertDialog.show();
We talked about adding the this.delayed function here on the mobile patch, will this be addressed later ?

2024-03-07 16:56 UTC, tommasini commented on android/src/main/java/com/reactnativecommunity/webview/RNCWebChromeClient.java
> +            alertDialog.show();
Nevermind it was updated here on this [PR](https://github.com/MetaMask/react-native-webview-mm/pull/10)

2024-03-07 16:56 UTC, tommasini approved these changes
LGTM!

2024-03-14 14:43 UTC, sethkfman approved these changes
LGTM

2024-03-26 16:41 UTC, merged